# Generated by Django 3.1.2 on 2020-11-05 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='tx_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_from', to='mybank.customers'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tx_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_to', to='mybank.customers'),
        ),
    ]
